### ISSUE TITLE
[2.0.0-beta.4] Not working - can't find one of my build plugins

### ISSUE THREAD

**Issue by clayne11** [gadicc/meteor-hmr#105]
When I change a file the accelerator complains that it can't find `react-hot-loader/babel`.

```
I20160606-12:56:02.294(-4)? info: [2016-06-06 16:56:02][MailChimpService] : Updated user with email curtis.s.layne@gmail.com on mailing list c8cf4db14e
   Scanning local packages                   |
[gadicc:hot] Accelerator (aBh): Build plugin error.  Skipping this time.  The error was: { [Error: Cannot find module 'react-hot-loader/babel'] code: 'MODULE_NOT_FOUND' }
```

**Comment by menelike** [comment]
I had the exact same error when I used `fabricjs`. I thought that this must be related to `fabricjs` and its `canvas` dependencies. I had to wrap `fabricjs` in a meteor package for client only to make it work.

Still curious what causes this.

**Comment by gadicc** [comment]
Is this in a meteor package or the app?

What version of Meteor?

**Comment by menelike** [comment]
I had this error when I used the [fabric npm package](https://www.npmjs.com/package/fabric) within `METEOR@1.3.3-beta.2`. I haven't tested other Meteor versions, I'm not event sure if this is an issue related to `HMR` at all. I switched to https://github.com/ryanswapp/fabricjs instead of the meteor package. This is why I choose to not report an issue.

@clayne11 any chance to make this reproducible?

**Comment by clayne11** [comment]
This is happening in my main app. Meteor `1.3.3-rc.0`.

**Comment by gadicc** [comment]
I don't have any solutions just more questions :/  Since unfortunately I'm unable to reproduce.  If you have a moment, maybe you can see if it works in a fresh project, and if it doesn't, put that on github just in case it breaks also on my system.  Otherwise:

1. Do you still have a `client/.babelrc` ?  If it's empty, any difference if you delete it?
1. Are you running `meteor` from within your project root, as opposed to a subdirectory?
1. `node_modules/react-hot-loader` does exist right?  Assuming this would throw an error on regular meteor load otherwise.

@menelike, btw, the error you received with fabricjs was identical, right?  Also for `react-hot-loader/babel` or for something related to fabricjs?

I think probably to hunt this down we'll need to use a local checkout of Meteor which has extra logging in `tools/isobuild/compiler-plugin.js` to see what's different between the Meteor vs accelerator run.  I just wish I could reproduce on my side.

**Comment by clayne11** [comment]
I don't have a `client/.babelrc` anymore. I removed it when I updated to Meteor `1.3.3` as it was empty anyways since the switch to `react-hot-loader/babel`.

**Comment by clayne11** [comment]
Now I'm using Meteor `1.3.3-rc.4` and I'm getting `exited with code: 1` with `gadicc:ecmascript-hot@2.0.0-beta.4`. Works fine with `ecmascript`.

**Comment by gadicc** [comment]
Can you clone https://github.com/gadicc/mantra-sample-blog-app-hot (which uses those same versions) and see if it works there?  Would love to figure out if it's something specific to your app / system / OS.

**Comment by gadicc** [comment]
That uses an updated `beta.5`, which you can try do, but I don't believe it will have any impact on your issue (it includes the string translation fix, and forces more recent meteor core versions, but issue affected the initial Meteor build too, not just accelerator updates).

**Comment by menelike** [comment]
@gadicc This can be reproduced per https://github.com/menelike/mantra-sample-blog-app-hot/commit/eb6c8c7cac6f1000d8ab22d796092a3b4031a05d

Start the app, trigger a client refresh and you should see the following output.

```
[[[[[ ~/mantra-sample-blog-app-hot ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
=> Starting gadicc:hot-build Accelerator (yBJ) on port 3002.

=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
                                              
[gadicc:hot] Accelerator (yBJ): Warning: unable to resolve "react-hot-loader/babel" in plugins of /Users/foo/mantra-sample-blog-app-hot/.babelrc
=> Client modified -- refreshing (x2)
```

I have not tested this on pure Meteor projects, as mentioned before I think this might not be related to `HMR`.

Moreover I need to apologize as I may have mixed `fabric` with `ostrio:cookies`, though `fabric` produced an error as well (might be a pure Meteor issue again). I'll try to make a reproducible case for that as well and create an new issue if I succeed.

**Comment by clayne11** [comment]
I just installed `2.0.0-beta.5` and it seems to be working better.

I get the warning on the first file save (but the hot-reload seems to go through), then I don't get the warning anymore afterwards.

**Comment by menelike** [comment]
@clayne11 confirmed. 
Though in my current project `gadicc:ecmascript-hot@2.0.0-beta.5` and `METEOR@1.3.3-rc.5` do not produce any error/warning at all.

**Comment by clayne11** [comment]
I'm using the same version and still getting the initial warning. I'm OK with closing this though, it's not affecting anything as far as I can tell.

**Comment by clayne11** [comment]
I was mistaken, this issue is still happening. Hot-reloading works if I'm using a file that doesn't require any of my custom transforms, but the transformation fails once it tried to transform one of the files using, for example, `class-properties-transform`.

**Comment by gadicc** [comment]
I'm working on this.  Bringing in a lot more stuff from Meteor.  Probably overkill for this problem but will hopefully address other issues in the future before they happen.  Quite a process though.  Should have something out by the end of the weekend.

**Comment by gadicc** [comment]
ok the planned solution was a fail but I think I found a very good compromise.  I need to spend more time testing before I can publish something, but if you like you can run from master and see if this solves the problem (unfortunately I was never able to reproduce on my side, so I can't be sure, but I've totally changed the resolver logic for this case).

**Comment by clayne11** [comment]
I ran from master and I can confirm that the issue is fixed! Thanks :)

**Comment by gadicc** [comment]
Yay!  Thanks!  Will get the release out later this week, with a few other fixes.
