### ISSUE TITLE
Warning when root component is Router from react-router

### ISSUE THREAD

**Issue by kachkaev** [gadicc/meteor-hmr#64]
## Description of Problem

I'm trying to use `meteor-hmr` while keeping Router from [`react-router`](https://github.com/reactjs/react-router) as my top-level component. Everything seems to be working except that I get a warning with every hot update.

```
[gadicc:hot] Updating ["/imports/ui/components/Abc.jsx"]
Warning: [react-router] You cannot change <Router routes>; it will be ignored
```

Here is my `main.jsx`:

```jsx
import 'react-hot-loader/patch';
import React from 'react';
import { browserHistory } from 'react-router';
import { Meteor } from 'meteor/meteor';
import { AppContainer as HotLoaderAppContainer } from 'react-hot-loader';
import ReactDOM from 'react-dom';
import AppRoutes from '/imports/startup/client/routes.jsx';

Meteor.startup(() => {
  const appElement = document.getElementById('app');

  const renderApp = (CurrentAppRoutes) => {
    ReactDOM.render(
      <HotLoaderAppContainer>
        <CurrentAppRoutes browserHistory={ browserHistory } />
      </HotLoaderAppContainer>,
      appElement
    );
  };

  renderApp(AppRoutes);

  if (module.hot) {
    module.hot.accept(
      '/imports/startup/client/routes.jsx',
      () => {
        renderApp(require('/imports/startup/client/routes.jsx').default);
      }
    );
  }
});
```

`/imports/startup/client/routes.jsx`:
```jsx
import React from 'react';
import { Router, Route, IndexRoute } from 'react-router';

import AppContainer from '/imports/ui/containers/AppContainer.jsx';
import StandardPage from '/imports/ui/layouts/StandardPage.jsx';

import Home from '/imports/ui/pages/Home.jsx';

import About from '/imports/ui/pages/standard/About.jsx';
import Partners from '/imports/ui/pages/standard/Partners.jsx';
import NotFound from '/imports/ui/pages/standard/NotFound.jsx';

const AppRoutes = ({ browserHistory }) => (
  <Router history={ browserHistory }>
    <Route path="/" component={ AppContainer }>
      <IndexRoute component={ Home } />
      <Route component={ StandardPage } >
        <Route path="about" component={ About } />
        <Route path="partners" component={ Partners } />
        <Route path="*" component={ NotFound } />
      </Route>
    </Route>
  </Router>
);

AppRoutes.propTypes = {
  browserHistory: React.PropTypes.object,
};

export default AppRoutes;
```

I guess I understand what causes the warning but cannot come up with an idea on how to overcome it. Could anyone please help?

## Environment

* Meteor version: 1.3.2.4
* ecmascript-hot version: 1.3.2-refactor.7
* react-hot-loader: 3.0.0-beta.0
* Operating System: OSX

**Comment by tastemeru** [comment]
Just want to thank you for the example code, because without it I will never handle updating to the new version of HMR. And I even have the same error.

PS @gadicc it would be helpful if you add a sample code how to integrate HRM with react router [here](https://github.com/gadicc/meteor-hmr/blob/master/docs/Upgrading.md), because it's really complicated for newbies as me.

**Comment by clayne11** [comment]
You could try wrapping your root component in an `HOC` that doesn't do anything, or perhaps even a `div`.

Personally, I use `redux` so my Router is wrapped with the `Provider` component and I'm not seeing this warning.

**Comment by kachkaev** [comment]
Thanks for the response @clayne11! Could you please share an example of how this could be done?
I tried wrapping the `<Router>` into `<div>`, `<div key="router-wrapper">` and in a few other ways, but that did not help.

I agree with @tastemeru that explaining the trick in the docs would be great.

**Comment by gadicc** [comment]
Hey all.

First off, disclaimer, I don't use react-router :)

You should be aware that there was a lot of traffic about react-router in the [main RHL3 beta demo issue](https://github.com/gaearon/react-hot-boilerplate/pull/61).  As I understand it, the source of the error (and a bunch of problems in the alpha) is [react-router#2182](https://github.com/reactjs/react-router/issues/2182), but this has been worked around now with `react-hot-loader@^3.0.0-beta.1`.  If I understood correctly, everything works with this release, and the warning, while annoying, can be safely ignored.  So please try with this version and report back.

I agree and would love to add this to the docs.  @kachkaev, can I use your sample above? :)  Since I don't know any better.  The official RHLv3 docs will cover this too I guess, once they're ready.

**Comment by kachkaev** [comment]
Thanks for clarifying the things @gadicc! Sure, go ahead and copy my stuff if you want. I'm not sure what I came up with is perfect, but at least it works somehow.

**Comment by gadicc** [comment]
Thanks, @kachkaev!  Looks good to me.  I added this to the React_Hotloading docs with a mention in the Upgrading docs.  My only change was to assign the require to a variable first, which is totally unnecessary but makes things a bit clearer to newbies:

```js
    module.hot.accept('/imports/startup/client/routes.jsx', () => {
      const NextAppRoutes = require('/imports/startup/client/routes.jsx').default;
      renderApp(NextAppRoutes);
    });
```

**Comment by kachkaev** [comment]
Sorry for a potentially stupid question. But should this remove the warning by React Router? Although the app works even with it, the console gets cluttered pretty quickly, and something else may get missed.

**Comment by gadicc** [comment]
No, unfortunately as I understood it, this would need to be fixed in react-router.  Currently, react-hot-loader works around the problem, but it can't work around the warning :D  I think I linked to the relevant issues in an earlier comment, maybe there's been more progress since then... but I know the original issue has been open for quite a while I think.

I guess in theory you could override/wrap console.log/warn/error (can't remember which it is) to not output this exact error :)  Otherwise I'm happy to hear your console is so full of happy hot reloading :D
