### ISSUE TITLE
[gadicc:hot] /client/main.js is not hot and nothing requires it

### ISSUE THREAD

**Issue by rickmed** [gadicc/meteor-hmr#65]
main.js is my entry file in for the client in the meteor app (meteor-app/client/main.js)

I get the error in the title but of course nothing will require it since it is the entry file...

**Comment by clayne11** [comment]
I'm seeing the same thing.

**Comment by gadicc** [comment]
This error is usually correct, but clearly I haven't explained it very well :)

The first line you'll see looks like this:

```
[gadicc:hot] Updating ["/client/colors.js"]
```

From there:

1. We check if `/client/colors.js` can self accept, it can't, so we need to look at what files import it.
1. Say `colorImporter.js` imports this file; we check if it can accept a change for `colors.js`, but it can't, so we need to look at what files import *this* file.
1. `main.js` imports `colorImporter.js`, can it accept changes for `colorImporter.js`?  No.
1. So now we need to look for anything that imports `main.js` but nothing does, so that's why you get this error.

I'm going to make this clearer in the next version, but outputting the full import chain.  Although this is the correct behaviour for any update we can't handle, when we want the Meteor's HCP to come through (e.g. modifying a file that isn't covered by HMR logic...).

To work out whether or not this is a bug, can you check which file you're modifying, and where you expect the update to happen?  (e.g. where is your `hot.accept()` code, and does it specify it's direct import and knows how to handle the update).

**Comment by gadicc** [comment]
Ok, in the new version it now looks like this:
```
[gadicc:hot] Updating ["/client/non-hot-update.js"]
[gadicc:hot] No hot.accept() in /client/non-hot-update.js > /client/index.jsx
[gadicc:hot] HMR failed, allowing HCP...
```
which I think is a lot clearer.  I'm not updating `ecmascript-hot` yet to include this, but if you just temporarily add `gadicc:hot@0.0.23` you'll get the new version on the client.

**Comment by gadicc** [comment]
I also added this to the troubleshooting section of the README:

> **No hot.accept() in /client/non-hot-update.js > /client/index.jsx**

> *Previously: /client/main.js is not hot and nothing requires it*

> For hot-updating to work, either the file you changed must be able to self accept, or we'll climb the import chain looking for a file that can accept the change (i.e. it knows how to handle an update to a specific import).

> If you're trying to get React Hotloading working, see the [React Hotloading docs](docs/React_Hotloading.md).  If you're trying to get something else working, check the docs for the build plugin you think should be HMR-aware, or the [Handling Updates docs](docs/Handling_Updates.md) to get HMR working for other parts of your app.

> For anything else, this is probably the correct message, and Meteor's regular Hot Code Push (HCP) will come through and reload the page.  Hotloading only works for hotloading-aware code.  Changes to any other code *has to* restart the page to work correctly.

>You may find some other helpful info in [#65](https://github.com/gadicc/meteor-hmr/issues/65).

**Comment by clayne11** [comment]
The issue I was referring to was different. I'm having an issue where my the hot-reloader thinks my entry point has changed when it actually hasn't. I posted this in another issue though. I'm going to try `refactor.9` and see how that goes.

**Comment by rickmed** [comment]
@gadicc thanks for the quick response. 

Can you please clarify? (those links are dead).

Let's say a have an entry file main.js and it imports file.js. If I make changes to file.js it should trigger hot reloading, right? If I make changes to main.js it should too? or do I have to include additional code to main.js?

**Comment by clayne11** [comment]
You shouldn't really need to hot-reload your entry point. Once you set up your entry point to the app it should very rarely change. What you want to hot-reload is your root container for your app which contains all of your routes or whatever other app components that you have.

**Comment by rickmed** [comment]
@clayne11 but in case, when I change file.js (the one being imported) I also get main.js is not hot and nothing requires it and it triggers meteor's reload instead of hot reloading

**Comment by clayne11** [comment]
Ah I see - that was my original understanding of your issue. I was having the same issue with `gadicc:ecamscript-hot@1.3.2-refactor.7`. Have you updated to `gadicc:ecmascript-hot@1.3.2-refactor.9`? That fixed the issue for me.

**Comment by gadicc** [comment]
Oh!  If this fixed the problem for you, I think it's because maybe you had something like:

```js
import Something from './Something';

// i.e. the dep specified doesn't match what you used for the import statement
module.hot.accept('./Something.js', ....);
```

but we should still cover this case, so I made the checker more flexible.  That's the only change I made I think (aside from more debug code and changes to the file watcher).

**Comment by clayne11** [comment]
@gadicc yup that's exactly what it was for me.

**Comment by rickmed** [comment]
@gadicc so I updated to refactor.9.
Now I'm getting this when I change client/index.js:

[gadicc:hot] Updating ["/imports/client/index.js"]
hot.js:66 [gadicc:hot] No (relevant) hot.accept() in /imports/client/index.js > /client/main.js.  Need to reload.
(it triggers then meteor's reload)
My structure is:

meteor-app-root/client/main.js:
import '/imports/client'

meteor-app-root/imports/client/index.js:
code...

**Comment by clayne11** [comment]
Can you post your repo? There's several pieces that need to be set up properly here and simply posting your file structure doesn't detail all the possible places you could have a configuration issue.

**Comment by rickmed** [comment]
@clayne11 https://github.com/rickmed/Flexbot-2. Also, I'm getting duplicates of babelrc files (not sure why...)

**Comment by clayne11** [comment]
The main issue is that you haven't actually set anything up to accept hot code pushes. I'm not sure why you're seeing duplicate `.babelrc` files, but that's a separate issue.

Your [main file](https://github.com/rickmed/Flexbot-2/blob/master/meteor-app/imports/client/index.js) needs to be split into two: one file where you define your main container (`App`) and export it, then another where you import it, render it, and accept hot code pushes.

See the [docs](https://github.com/gadicc/meteor-hmr/blob/master/docs/React_Hotloading.md) for more info.

**Comment by rickmed** [comment]
@clayne11 thank you! (I guess I thought I've had set up hot reloading following another readme). Sorry for the inconveniences
@gadicc

**Comment by gadicc** [comment]
thanks @clayne11 for helping out! :D

@rickmed, sure, no worries...  were you upgrading from an earlier release?  We previously used a different version of react-hot-loader, which was simpler to setup but had a lot of problems.  The new version (currently in beta) addresses all these issues but involves a little more work (initially) for a better structured app.  Gearing up for this to be in our next stable release, so please let us know if anything is unclear in the docs.  (And yeah sorry, those dead links were because I pasted into the issue, but they'll work from within the README).

Re the duplicate babelrcs, not entirely sure what you meant, but yeah, please open another issue for that.  But also FYI official babelrc support from Meteor is milestoned for the next release (1.3.3) but they seem pretty tied up upgrading Meteor to use newer versions of node right now.

**Comment by rickmed** [comment]
@clayne11 super clear instructions. I got it working. 

Yeah, reducing that boilerplate would help a lot I think.

About the duplicate babelrcs it happened when I upgrated to refactor.9. I had a babelrc file in the root folder and it created another 0.babelrc file right next to it.

Cool library!

**Comment by gadicc** [comment]
Great stuff, thanks for reporting back!

There's no code in meteor-hmr to create filenames like `0.babelrc`.  My only guess is that maybe you had the file open in your editor and it tried to play it safe, but that's a bit of a leap.  Does the file stay away when you delete it?  Please do open another issue for this if the problem recurs, but I'm pretty sure it's not from us :D

Thanks for the kind words!
