### ISSUE TITLE
Meteor is killed when comiting changes

### ISSUE THREAD

**Issue by dagatsoin** [gadicc/meteor-hmr#66]
When you `git commit` your changes in another terminal window while Meteor is running, the process is not properly killed. It displays `Your server/.babelrc was changed, please restart Meteor.`

Then if you want for example to clean your meteor folder by doing `meteor reset` you will be warned that `reset: Meteor is running.`.

So I guess the killing process is buggy as some point.

**Comment by gadicc** [comment]
Hey :)  Ok, two issues here:

**1) git commit**

There's nothing `git commit` does that should be affecting your `babelrc` (case in point, I do this I don't know how many times a day in different projects and have never seen this :)).  Is there anything in your  `.git/hooks/{pre,post}-commit` files (if they exist) that could be affecting this file or directory?

**2) failure to exit**

Most of the time this works but sometimes it does fail and/or doesn't clean up as nicely as a real Meteor quit.  Unfortunately I have to mark this as `wont-fix` because a) there's nothing else I can do from within the confines of a build plugin, and b) Meteor is expected to get official `.babelrc` support soon (it's milestoned for Meteor 1.3.3).

Nevertheless, thanks for reporting, and sorry I can't offer more help yet, but sounds like the next Meteor will solve both of these for you, regardless.

**Comment by dagatsoin** [comment]
Hey @gadicc :)
Thx for your answer. No I have not set any pre.post script. I will close this and wait for the 1.3.3 to see if I run the same issue.
