### ISSUE TITLE
Uncaught Error: Cannot find module 'babel-runtime/helpers/get'

### ISSUE THREAD

**Issue by shoetten** [gadicc/meteor-hmr#68]
Hey there,

i just bumped into this. It's a mantra styled app, in case that's relevant.
The error goes away when i 1) switch to the regular ecmascript or 2) delete the file mentioned below.

* [x] I switched back to the regular `ecmascript` and the problem went away.

This is the stack trace:
```
websocket.js:16[gadicc:hot] Connected and ready.
modules-runtime.js?hash=a5461dd…&hot=1:113 Uncaught Error: Cannot find module 'babel-runtime/helpers/get'
	require @ modules-runtime.js?hash=a5461dd…&hot=1:113
	meteorInstall.client.modules.users.components.auth_forms.js @ routes.js:5
	fileEvaluate @ modules-runtime.js?hash=a5461dd…&hot=1:176
	require @ modules-runtime.js?hash=a5461dd…&hot=1:110(anonymous function) @ app.js?hash=498eae2…:2198
```

The error only occurs on this particular file:

<details>
<summary>`client/modules/users/components/auth_forms.js`</summary>
```js
import {Accounts, STATES} from 'meteor/std:accounts-ui';

class AuthForms extends Accounts.ui.LoginForm {
  fields() {
    const {formState} = this.state;
    if (formState === STATES.SIGN_UP) {
      return {
        ...super.fields(),
        firstname: {
          id: 'firstname',
          hint: 'Enter firstname',
          label: 'firstname',
          onChange: this.handleChange.bind(this, 'firstname'),
        },
      };
    }
    return super.fields();
  }

  signUp(options = {}) {
    const { firstname = null } = this.state;
    if (firstname !== null) {
      options.profile = Object.assign(options.profile || {}, {
        firstname,
      });
    }
    super.signUp(options);
  }
}

export default AuthForms;
```
</details>

## Environment

* Meteor version: 1.3.2.4
* ecmascript-hot version: 1.3.2-refactor.9
* Operating System: OS X 10.11

Any ideas?

**Comment by gadicc** [comment]
Mmm, ok, first can you check your `.meteor/versions` file and see if `babel-runtime` is at `0.1.8`?  If not, it might be because this package was updated in Meteor 1.3.2.4 and we only force 1.3.2.  You can try `meteor update` or maybe `meteor add babel-runtime` and then `meteor update`.

Otherwise, this could be a discrepancy with babel plugins/presets.  The (current) stock `ecmascript` uses `babel-compiler` without `.babelrc` support, and just the Meteor preset.  What do your `.babelrc` files look like?  To test as close to Meteor as possible, you should only have:

```js
{
  "presets": [ "meteor" ]
}
```

(although `react-hot-loader/babel` shouldn't affect this either).  In theory anything should be ok as long as you still have the `meteor` preset there.  And up to date.  We should warn you if you don't have `babel-preset-meteor': '^6.6.7` for this release.

Hopefully it's one of these.

**Comment by shoetten** [comment]
Thanks for the pointers, it works now.
My .babelrc was looking like this,
````js
{
  "presets": [
    "meteor",
    "es2015",
    "react"
  ]
}
```
which turned out to be the problem. Removing the es2015 preset did the trick.
I guess it shouldn't have been there in the first place, since the meteor preset knows best what es2015 transforms it supports.. Unsure though, why it conflicted with this particular file.

Just for reference, i was using `babel-runtime@0.1.8` with
```js
"babel-preset-es2015": "^6.6.0",
"babel-preset-meteor": "^6.6.7",
"babel-preset-react": "^6.5.0",
```

Thanks again.

**Comment by gadicc** [comment]
Great!  Happy I got this 1st time, not doing as well in some other issues ;)

Yeah, unfortunately things can get quite tricky with the load order of plugins and presets... 

Ok since you asked :D

When your transpiled code needs to rely on an ES6 feature on a new global, like Set, or an augmented global from ES5, like, Array#includes, there are two ways to do it.  The first involves `babel-polyfill`, which adds these functions into the global scope (so now, anything can use Array#includes), but this can potentially break other parts of your app or conflict with other polyfills, and is considered bad practice.  The alternative is to transform these calls to require() the appropriate function from `babel-runtime`, which is what we do in Meteor, although via a few Meteor versions of these packages.

So that's why certain files can trigger this and not others.  Not 100% sure how the load order led to one of the helpers not being bundled, but there it is :>

**Comment by shoetten** [comment]
Alright, thanks for the advice! :)
