### ISSUE TITLE
Hot loading with Blaze + React

### ISSUE THREAD

**Issue by billyvg** [gadicc/meteor-hmr#79]
We have an application that uses Blaze layouts as our root layouts, and brings in React components. Is it possible to use the new version of `react-hot-loader` with this setup? We don't have a "root" React component.

**Comment by gadicc** [comment]
Sure.  It's a little extra work though, because before anywhere where you'd mounting a React component, you have to wrap it in an `AppContainer`.

Are you using `react-template-helper` for this?  Maybe it could be forked to do this automatically if react-hot-loader is installed, which could make this a lot easier.  Unfortunately I don't have any time to do it myself :(

**Comment by billyvg** [comment]
Yeah we're using `react-template-helper` -- how can I check if `react-hot-loader` is installed?

**Comment by gadicc** [comment]
Just with `try/catch` and `require()` :)  See e.g. https://github.com/tmeasday/check-npm-versions/blob/master/check-npm-versions.js

**Comment by billyvg** [comment]
Will give that a shot then, thanks!

**Comment by gadicc** [comment]
Awesome!  Keep me posted.  If you end up publishing it I'd love to make a note of it in the React docs.
